### ISSUE TITLE
Where can i find the image stack images and the diff stack imaages

### ISSUE THREAD

**Issue by anirudhtopiwala** [lmb-freiburg/flow_rl#1]
When running the Chaser2d-v2, what input should I give to the argument --diff_frames. When I run what is given in the ReadMe, I get :
```
run_mujoco_imvec.py: error: argument --diff_frames: expected one argument
```

**Comment by amiranas** [comment]
There was a mistake in the ReadMe. It should have been `--stack_frames True` for running with normal image stack, and both `--stack_frames True --diff_frames True` for stacking with image difference. Thank you for finding it.
